#!/bin/bash

# Defina os nomes dos processos a serem verificados
processo1="rclone"
processo2="rsync"
processo3=""

# Função para verificar e encerrar um processo
verificar_e_encerrar() {
    local nome_processo="$1"
    if [ -n "$nome_processo" ]; then
        # Verifica se o processo está em execução
        processos=$(pgrep -x "$nome_processo")
        if [ -n "$processos" ]; then
            echo "Instancias do processo '$nome_processo' encontradas com os seguintes PIDs: $processos"
            echo "Encerrando as instancias..."
            # Encerra os processos
            kill -9 $processos
            if [ $? -eq 0 ]; then
                echo "Todas as instancias de '$nome_processo' foram encerradas com sucesso."
            else
                echo "Erro ao tentar encerrar as instancias de '$nome_processo'."
            fi
        else
            echo "Nenhuma instancia do processo '$nome_processo' está em execucao."
        fi
    else
        echo "Nome do processo vazio. Nada a fazer."
    fi
}

# Verifica e encerra os processos definidos
verificar_e_encerrar "$processo1"
verificar_e_encerrar "$processo2"
verificar_e_encerrar "$processo3"
