#!/bin/bash

# Defina o diretório a ser verificado
diretorio="/dados/lixeira/lixeira"

# Função para excluir o diretório
excluir_diretorio() {
    if [ -d "$diretorio" ]; then
        echo "Removendo o diretório: $diretorio"
        rm -rf "$diretorio"
        echo "Diretório removido com sucesso."
    else
        echo "O diretório $diretorio não existe."
    fi
}

# Verifique se o script foi executado com o parâmetro "certeza"
if [ "$1" == "certeza" ]; then
    excluir_diretorio
    exit 0
fi

# Pergunta ao usuário se deseja continuar
echo "O diretório definido é: $diretorio"
read -p "Deseja remover este diretório? (sim/nao): " resposta

if [[ "$resposta" == "sim" ]]; then
    excluir_diretorio
else
    echo "Operação cancelada pelo usuário."
fi
