#!/bin/bash


#menores primeiro
#rclone sync CarboAlba-R:dr/bkp/ 161-Tank-L:alba/bkp/ --progress --retries 3 --low-level-retries 10 --transfers 20  --order-by size,asc --stats 1s --timeout 1h

#maiores primeiro
rclone sync CarboAlba-R:dr/bkp/ 161-Tank-L:alba/bkp/ --progress --retries 3 --low-level-retries 10 --transfers 20  --order-by size,desc --stats 1s --timeout 1h
