#!/bin/bash

# Define o diretório de destino padrão
TARGET_DIR="/work"

# Verifica se um argumento foi passado; se sim, usa-o como diretório de destino
if [ -n "$1" ]; then
    TARGET_DIR="$1"
fi

# Exibe o diretório de destino
echo "Alvo definido para: $TARGET_DIR"

# Verifica e altera permissões apenas se necessário
echo "Alterando permissoes para 777 onde necessario..."
find "$TARGET_DIR" \! -perm 777 -exec chmod 777 {} +

# Verifica e altera proprietário e grupo para root:root apenas se necessário
echo "Alterando proprietario e grupo para root:root onde necessario..."
find "$TARGET_DIR" \! -user root -o \! -group root -exec chown root:root {} +

echo "Processo concluído."
