#!/bin/bash


#bash <(wget -qO- https://raw.githubusercontent.com/atedim/zz/main/zz_instala)


#bash <(curl -s https://raw.githubusercontent.com/atedim/zz/main/zz_instala)

###Testa ROOT###
if [[ $EUID -ne 0 ]]; then
   echo "Rode o Script como ROOT" 
   exit
fi
###Testa ROOT###

# Prepara instalações #
apt update && apt upgrade -y && apt autoremove && apt autoclean && apt clean
# Prepara instalações #

###instala basicos###
#apt install ntpdate rcconf mc rsync cifs-utils samba mergerfs htop bmon curl iptraf net-tools gdu etherwake screen mdadm rclone -y
apt install bmon htop rclone rsync sshpass dos2unix mc msmtp msmtp-mta sharutils ntpdate curl bc rcconf cifs-utils samba mergerfs iptraf net-tools gdu etherwake screen mdadm -y
###instala basicos###


# Ajusta data e hora do sistema
ntpdate pool.ntp.org >> /dev/null


# Configurações dos caminhos
caminho_repositorio="https://raw.githubusercontent.com/atedim/zz/main"
caminho_scripts="/etc/scripts"
caminho_bkp="/etc/scripts/old"
#caminho_scripts="/etc/test"
#caminho_bkp="/etc/test/old"


DATA=$(date +%d%m%Y)
progs="$caminho_scripts/list.conf"

# Verificar e criar pastas caso não existam
[ ! -d "$caminho_scripts" ] && mkdir -p "$caminho_scripts"
[ ! -d "$caminho_bkp" ] && mkdir -p "$caminho_bkp"

# Baixar o arquivo list.conf
curl -s "$caminho_repositorio/list.conf" -o "$progs"
if [ $? -ne 0 ]; then
    echo "Erro ao baixar list.conf. Verifique o repositório ou a conexão."
    exit 1
fi

# Verificar se list.conf existe
if [ ! -f "$progs" ]; then
    echo "Arquivo $progs não encontrado."
    exit 1
fi

# Ajusta permissoes
chmod -R 777 $caminho_scripts
chmod -R 777 $caminho_bkp
chown root:root -R $caminho_scripts
chown root:root -R $caminho_bkp

# Ler cada linha de list.conf e baixar os arquivos
while read -r arquivo; do
    if [ -n "$arquivo" ]; then
        # Caminho completo do arquivo no diretório de scripts
        arquivo_destino="$caminho_scripts/$arquivo"

        # Verificar se o arquivo já existe
        if [ -f "$arquivo_destino" ]; then
            # Mover o arquivo antigo para a pasta de backup com a data
            mv "$arquivo_destino" "$caminho_bkp/$DATA.$arquivo.old"
            chmod u-x "$caminho_bkp/$DATA.$arquivo.old"
        fi

        # Baixar o novo arquivo do repositório
        curl -s "$caminho_repositorio/$arquivo" -o "$arquivo_destino"
        
        # Tornar o novo arquivo executável
        chmod u+x "$arquivo_destino"
        
        echo "Arquivo $arquivo atualizado e configurado em $caminho_scripts."
    fi
done < "$progs"


# Ajusta permissoes
chmod -R 777 $caminho_scripts
chmod -R 777 $caminho_bkp
chown root:root -R $caminho_scripts
chown root:root -R $caminho_bkp


###Insere Script to PATH###
sed -i -e '$a\' ~/.bashrc && echo 'export PATH=$PATH:/etc/scripts' >>~/.bashrc && sed -i -e '$a\' ~/.bashrc
###Insere Script to PATH###


echo "Processo concluído."
echo "Recomendado reinicio completo."
