#!/bin/bash

# Define o arquivo de configuracao e a customizacao desejada do prompt
BASHRC="$HOME/.bashrc"
NEW_PROMPT="PS1='\\[\\033[1;34m\\]\\u\\[\\033[0m\\]@\\[\\033[1;33m\\]\\h\\[\\033[0m\\]_\\[\\033[1;32m\\]\$(hostname -I | cut -d\" \" -f1)\\[\\033[0m\\]:\\w\\$ '"

# Verifica se há uma linha PS1 existente em ~/.bashrc
CURRENT_PROMPT=$(grep -E '^PS1=' "$BASHRC")

if [ -n "$CURRENT_PROMPT" ]; then
    # Exibe o prompt atual
    echo "Uma customizacao de prompt ja existe no ~/.bashrc:"
    echo "$CURRENT_PROMPT"

    # Pergunta ao usuário se deseja substituir pelo novo prompt
    read -p "Deseja substituir pela nova customização de prompt? (s/n): " choice
    if [[ "$choice" =~ ^[Ss]$ ]]; then
        # Substitui o prompt existente pelo novo
        sed -i "s|^PS1=.*|$NEW_PROMPT|" "$BASHRC"
        echo "Prompt substituido com sucesso."
    else
        echo "A customizacao nao foi alterada."
    fi
else
    # Adiciona a nova customizacao de prompt no final do ~/.bashrc
    echo "$NEW_PROMPT" >> "$BASHRC"
    echo "Nova customizacao de prompt adicionada com sucesso."
fi

###Insere Script to PATH###
sed -i -e '$a\' ~/.bashrc && echo 'export PATH=$PATH:/etc/scripts' >>~/.bashrc && sed -i -e '$a\' ~/.bashrc
###Insere Script to PATH###


# Aplica as mudancas imediatamente
source "$BASHRC"
